// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/faturamento": {
            "get": {
                "description": "Retorna o histórico de notas fiscais com seus itens",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "faturamento"
                ],
                "summary": "Listar todas as notas",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.NotaFiscal"
                            }
                        }
                    }
                }
            },
            "post": {
                "description": "Cria uma nota fiscal, abate o estoque dos produtos e salva os itens em uma transação única.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "faturamento"
                ],
                "summary": "Abrir nova Nota Fiscal",
                "parameters": [
                    {
                        "description": "Dados da Nota e Itens",
                        "name": "nota",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.NotaFiscal"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/faturamento/{id}/fechar": {
            "patch": {
                "description": "Atualiza o status para Fechada e deduz o estoque dos produtos",
                "tags": [
                    "faturamento"
                ],
                "summary": "Fechar e Imprimir Nota Fiscal",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID da Nota Fiscal",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/produtos": {
            "get": {
                "description": "Retorna todos os produtos do banco de dados",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "produtos"
                ],
                "summary": "Listar produtos",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.Produto"
                            }
                        }
                    }
                }
            },
            "post": {
                "description": "Salva um novo produto no banco de dados",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "produtos"
                ],
                "summary": "Cadastrar novo produto",
                "parameters": [
                    {
                        "description": "Dados do Produto",
                        "name": "produto",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.Produto"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/models.Produto"
                        }
                    }
                }
            }
        },
        "/produtos/{id}/baixa": {
            "patch": {
                "description": "Subtrai uma quantidade do saldo de um produto específico",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "produtos"
                ],
                "summary": "Dar baixa no estoque",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID do Produto",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Quantidade a subtrair (ex: {",
                        "name": "quantidade",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "models.NotaFiscal": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "itens": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.NotaFiscalItem"
                    }
                },
                "numero_sequencial": {
                    "type": "integer"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "models.NotaFiscalItem": {
            "type": "object",
            "properties": {
                "descricao_produto": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "nota_id": {
                    "type": "integer"
                },
                "produto_id": {
                    "type": "integer"
                },
                "quantidade": {
                    "type": "integer"
                }
            }
        },
        "models.Produto": {
            "type": "object",
            "properties": {
                "codigo": {
                    "type": "string"
                },
                "descricao": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "saldo": {
                    "type": "integer"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
